version: "3.8"

services:

  gui:
    depends_on:
      - referee
    build: ./apps/gui
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "127.0.0.1:$GUI_LOCAL_PORT:$GUI_LOCAL_PORT"
    volumes:
      - ./node_modules:/usr/src/app/node_modules
      - ./packages:/usr/src/app/packages

    stdin_open: true
    tty: true
    networks:
      - tick-tack-zeitgeist-network

  referee:
    depends_on:
      - mongodb
    build: ./apps/referee
    restart: unless-stopped
    env_file: ./.env
    environment:
      - WORKSHOP_ORACLE_SEED=$WORKSHOP_ORACLE_SEED
      - WORKSHOP_ORACLE_PASSPHRASE=$WORKSHOP_ORACLE_PASSPHRASE
      - MONGODB_HOST=mongodb
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_DATABASE=avatar
      - MONGODB_DOCKER_PORT=$MONGODB_DOCKER_PORT
      - REFEREE_API_PORT=$REFEREE_API_PORT
      - VITE_ZEITGEIST_WS=$ZEITGEIST_WS
    ports:
      - "127.0.0.1:$REFEREE_API_PORT:$REFEREE_API_PORT"
    stdin_open: true
    tty: true
    networks:
      - tick-tack-zeitgeist-network

  mongodb:
    image: mongo:5.0.6
    restart: unless-stopped
    env_file: ./.env
    environment:
      - ENV=$ENV
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - "127.0.0.1:$MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT"
    volumes:
      - db:/data/db
    networks:
      - tick-tack-zeitgeist-network

networks:
  tick-tack-zeitgeist-network:
    driver: bridge

volumes:
  db:
